<div class="jumbotron" align="center">
    <h1><?php echo sprintf($this->translate('Our %sProducts%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>


<?php if (count($products)) {?>
    <div class="row product-header">
        <div class="col-md-12">
            <div class="col-md-3">#</div>
            <div class="col-md-3">Title</div>
            <div class="col-md-3">Price</div>
            <div class="col-md-3">Image</div>
        </div>
    </div>
    <hr>
<?php } else { echo 'no Products';} ?>

<div class="row product-list">
    <?php foreach ($products as $product) : ?>
        <div class="col-md-12">
            <div class="col-md-3"><?php echo $product->getId() ?></div>
            <div class="col-md-3"><?php echo $product->getTitle() ?></div>
            <div class="col-md-3"><?php echo $product->getPrice() ?></div>
            <div class="col-md-3">
                <img width="100" height="100" class="product-image"
                     src="<?php echo $this->basePath().$product->getImage(); ?>" />
            </div>
        </div>
    <?php endforeach; ?>
</div>


<div class="row navigation">
<?php
    $countConst = Application\Controller\IndexController::NUMBER_OF_BLOG_ITEMS_PER_PAGE;
    if ($prev){ ?>
        <a href="/<?php echo ($current_page-1); ?>">
            <button type="button" class="btn btn-default">prev</button>
        </a>
    <?php } ?>
    <span class="text-center">
        <?php for ($i = 1; $i <= $pages; $i++) {?>
            <?php if ($i != $current_page): ?>
                    <a href="/<?php echo ($i); ?>">
                        <?php echo $i; ?>
                    </a>
            <?php else: ?>
                <a href="#" style="color: #ccc;">
                    <?php echo $i; ?>
                </a>
            <?php endif; ?>
        <?php }?>
    </span>
    <?php if ($next) { ?>
        <a href="/<?php echo ($current_page+1); ?>" class="pull-right">
            <button type="button" class="btn btn-default">next</button>
        </a>
    <?php } ?>
</div>


<div id="myModal" class="modal fade image-view-modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Full Image</h4>
            </div>
            <div class="modal-body">
                <div id="full-image"></div>
            </div>

        </div>
    </div>
</div>


<script type="text/javascript">
    $('.product-list').on('click', '.product-image', function(){
        $('#full-image').css('background','url("' + $(this).attr("src") + '")');
        $('#myModal').modal('show');
    });
</script>